spring:
  application:
    name: pedidos-api
  datasource:
    url: jdbc:mysql://${DB_HOST_PEDIDOS}/${DB_NAME_PEDIDOS}?createDatabaseIfNotExist=true
    username: ${DB_USER_PEDIDOS}
    password: ${DB_PASSWORD_PEDIDOS}
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    serviceUrl:
      # URL do Eureka Server.
      # O cliente utiliza esse endereço para localizar o Service Registry
      defaultZone: http://localhost:8081/eureka
  instance:
    # Define um identificador único para cada instância do serviço no Eureka,
    # combinando o nome da aplicação com um valor aleatório.
    instanceId: ${spring.application.name}:${random.int}

resilience4j:
  circuitbreaker:
    instances:
      cancelaPagamento:
        # Define o número de chamadas mais recentes consideradas
        # no cálculo da taxa de falhas do Circuit Breaker.
        slidingWindowSize: 3

        # Define a quantidade mínima de chamadas registradas
        # antes que o Circuit Breaker passe a avaliar a taxa de falhas.
        minimumNumberOfCalls: 2

        # Define o tempo em que o Circuit Breaker permanece no estado OPEN.
        waitDurationInOpenState: 60s

server:
  # Porta em que a aplicação será executada.
  # Ao usar "0", o Spring Boot atribui automaticamente uma porta aleatória disponível no sistema.
  port: 0